# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: ""
title: The A. J. Morris Group
email: a.j.morris.1@bham.ac.uk
author: Angela F Harper
description: > # "Write an awesome description for your new site here. 
  Density-Functional Theory and Energy Materials
copyright: 'Copyright &copy; 2020 Angela Harper. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/condensedmatter
  - title: google 
    url: https://scholar.google.com/citations?user=HWPGn8oAAAAJ&hl=en&oi=sra
  - title: linkedin
    url: https://www.linkedin.com/in/andrew-morris-96883024/

header_pages:
  - news/index.html

exclude:
  - Gemfile
  - Gemfile.lock
